@baseUrl = http://127.0.0.1:8000/api
@appUrl = http://127.0.0.1:8000

### 1. Registrar Usuário
# @name register
POST {{baseUrl}}/register
Content-Type: application/json
Accept: application/json

{
  "name": "Rodrigo",
  "email": "rodrigo.teste@email.com",
  "password": "password123"
}

### 2. Fazer Login (Caso já tenha registrado)
# @name login
POST {{baseUrl}}/login
Content-Type: application/json
Accept: application/json

{
  "email": "rodrigo.teste@email.com",
  "password": "password123"
}

### Pegamos o token retornado nas requisições acima
@token = {{login.response.body.access_token}}


### 3. Criar Link Encurtado
# @name createLink
POST {{baseUrl}}/links
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "destination_url": "https://www.google.com",
  "title": "Link para o Google"
}

### Pegamos o código gerado pelo link
@code = {{createLink.response.body.code}}


### 4. Testar Redirecionamento (Simulando acesso público)
GET {{appUrl}}/{{code}}
